# This is a basic workflow to help you get started with Actions
name: Create Archive
on: 
  push:
    tags:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'MythicSky.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
        
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "MythicSky.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
