# This is a basic workflow to help you get started with Actions
name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'MythicSky.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
        
    - name: Update release
      uses: johnwbyrd/update-release@v1
      with:
       token: ${{ secrets.YOUR_PRIVATE_SECRET_TOKEN }}
       asset: ./MythicSky.zip
